services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  database_data:
  pgadmin_data:
